### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by Protektor-Desura** [fHDHR/fHDHR_Locast#142]
```
version: '2.1'
services:
  fhdhr_locast:
    image: fhdhr_locast:0.4.6
    container_name: fhdhr_locast
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    ports:
      - 1900:1900 # SSD Cluster Port
      - 5004:5004 # Web & HDHR Port
    volumes:
      - /<docker-config-directory>/fhdhr_locast:/app/config
    restart: always
```
